// Generated by Wrangler on Wed May 08 2024 15:43:39 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	TURSO_CONNECTION_URL: "libsql://ai-notes-prod-callumk7.turso.io";
	TURSO_AUTH_TOKEN: string;
	AUTH_KEY: string;
}
