name = "game-master-remix-client"

[vars]
TURSO_CONNECTION_URL = "libsql://ai-notes-prod-callumk7.turso.io"
GAME_MASTER_URL = "http://localhost:8787"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d2b9c1b1743b43d791d74623bed4d03c"

